SELECT 
    NOMBRE_CENTRO_POBLADO,
    SUM (Q.NUMERO_QUEJAS) NUMERO, 
    LATITUD, 
    LONGITUD 
FROM 
    (
        SELECT 
            CAR_CARG_ANO ANIO, 
            LPAD(CAR_T1548_DANE_DEPTO, 2, 0)||LPAD(FE.CAR_T1548_DANE_MPIO,3,0)||LPAD(FE.CAR_T1548_DANE_CPOBLADO, 3, 0) CODIGO_CENTRO_POBLADO, 
            COUNT (DISTINCT(FE.CAR_T1548_RAD_RECIBIDO)) NUMERO_QUEJAS 
        FROM 
            CAR_T1548_RECLAMACIONES_ENE FE 
        WHERE 
                CAR_CARG_ANO = :ANIO_ARG 
            AND (IDENTIFICADOR_EMPRESA = :EMPRESA_ARG OR 0 = :EMPRESA_ARG)
            AND ( CAR_CARG_PERIODO = :PERIODO_ARG OR :PERIODO_ARG = 0 ) 
            AND ( 'ENERGIA' = :SERVICIO_ARG OR 'TODOS' = :SERVICIO_ARG )
            AND ( CAR_T1548_CAUSAL_DETALLE = :CAUSA_ARG OR :CAUSA_ARG = 0 ) 
            GROUP BY CAR_CARG_ANO, LPAD(CAR_T1548_DANE_DEPTO, 2, 0)||LPAD(FE.CAR_T1548_DANE_MPIO,3,0)||LPAD(FE.CAR_T1548_DANE_CPOBLADO, 3, 0), CAR_T1548_CAUSAL_DETALLE 
        UNION 
        SELECT 
            CAR_CARG_ANO ANIO, 
            LPAD(FG.CAR_T1552_DANE_DEPTO, 2, 0)||LPAD(FG.CAR_T1552_DANE_MPIO,3,0)||LPAD(FG.CAR_T1552_DANE_CPOBLADO, 3, 0) CODIGO_CENTRO_POBLADO, 
            COUNT (DISTINCT(FG.CAR_T1552_RAD_RECIBIDO)) NUMERO_QUEJAS 
        FROM 
            CAR_T1552_RECLAMACIONES_GAS FG 
        WHERE 
                CAR_CARG_ANO = :ANIO_ARG 
            AND (IDENTIFICADOR_EMPRESA = :EMPRESA_ARG OR 0 = :EMPRESA_ARG)
            AND (CAR_CARG_PERIODO = :PERIODO_ARG OR :PERIODO_ARG = 0 ) 
            AND ( 'GAS' = :SERVICIO_ARG OR 'TODOS' = :SERVICIO_ARG ) 
            AND ( CAR_T1552_CAUSAL_DETALLE = :CAUSA_ARG OR :CAUSA_ARG = 0 ) 
        GROUP BY CAR_CARG_ANO, LPAD(FG.CAR_T1552_DANE_DEPTO, 2, 0)||LPAD(FG.CAR_T1552_DANE_MPIO,3,0)||LPAD(FG.CAR_T1552_DANE_CPOBLADO, 3, 0), CAR_T1552_CAUSAL_DETALLE 
        UNION 
        SELECT 
            CAR_CARG_ANO ANIO, 
            LPAD(FGL.CAR_T1554_DANE_DEPTO, 2, 0)||LPAD(FGL.CAR_T1554_DANE_MPIO,3,0)||LPAD(FGL.CAR_T1554_DANE_CPOBLADO, 3, 0) CODIGO_CENTRO_POBLADO, 
            COUNT (DISTINCT(FGL.CAR_T1554_RAD_RECIBIDO)) NUMERO_QUEJAS 
        FROM 
            CAR_T1554_RECLAMACIONES_GLP FGL 
        WHERE 
                CAR_CARG_ANO = :ANIO_ARG 
            AND (IDENTIFICADOR_EMPRESA = :EMPRESA_ARG OR 0 = :EMPRESA_ARG)
            AND (CAR_CARG_PERIODO = :PERIODO_ARG OR :PERIODO_ARG = 0 ) 
            AND ( 'GLP' = :SERVICIO_ARG OR 'TODOS' = :SERVICIO_ARG )
        GROUP BY CAR_CARG_ANO, LPAD(FGL.CAR_T1554_DANE_DEPTO, 2, 0)||LPAD(FGL.CAR_T1554_DANE_MPIO,3,0)||LPAD(FGL.CAR_T1554_DANE_CPOBLADO, 3, 0), CAR_T1554_CAUSAL_DETALLE
    ) Q, 
    GIS_CENTRO_POBLADO G 
WHERE G.CODIGO_CENTRO_POBLADO = Q.CODIGO_CENTRO_POBLADO 
GROUP BY NOMBRE_CENTRO_POBLADO,LATITUD,LONGITU