SELECT 
    SERVICIO,
    IDENTIFICADOR_EMPRESA,
    CONVERT(ARE_ESP_NOMBRE, 'US7ASCII', 'WE8ISO8859P1'),
    CONVERT(NOMBRE_CENTRO_POBLADO, 'US7ASCII', 'WE8ISO8859P1'),
    COD_CAUSA,
    DESC_CAUSA,
    SUM (Q.NUMERO_QUEJAS) NUMERO, 
    LATITUD, 
    LONGITUD 
FROM 
    (
        SELECT 
            'ENERGIA' SERVICIO,
            IDENTIFICADOR_EMPRESA,
            CAR_CARG_ANO ANIO, 
            LPAD(CAR_T1548_DANE_DEPTO, 2, 0)||LPAD(FE.CAR_T1548_DANE_MPIO,3,0)||LPAD(FE.CAR_T1548_DANE_CPOBLADO, 3, 0) CODIGO_CENTRO_POBLADO, 
            CAR_T1548_CAUSAL_DETALLE COD_CAUSA,
            PQRENE.DESCRIPCION_CAUSAL DESC_CAUSA,
            COUNT (DISTINCT(FE.CAR_T1548_RAD_RECIBIDO)) NUMERO_QUEJAS 
        FROM 
            CAR_T1548_RECLAMACIONES_ENE FE, PQR_CAUSAL_ENE PQRENE  
        WHERE 
                CAR_CARG_ANO = :ANIO_ARG 
            AND FE.CAR_T1548_CAUSAL_DETALLE = PQRENE.IDENTIFICADOR_CAUSAL
            AND (IDENTIFICADOR_EMPRESA = :EMPRESA_ARG OR 0 = :EMPRESA_ARG)
            AND ( CAR_CARG_PERIODO = :PERIODO_ARG OR :PERIODO_ARG = 0 ) 
            AND ( 'ENERGIA' = :SERVICIO_ARG OR 'TODOS' = :SERVICIO_ARG )
            AND ( CAR_T1548_CAUSAL_DETALLE = :CAUSA_ARG OR :CAUSA_ARG = 0 ) 
            GROUP BY IDENTIFICADOR_EMPRESA,CAR_CARG_ANO, LPAD(CAR_T1548_DANE_DEPTO, 2, 0)||LPAD(FE.CAR_T1548_DANE_MPIO,3,0)||LPAD(FE.CAR_T1548_DANE_CPOBLADO, 3, 0), CAR_T1548_CAUSAL_DETALLE, PQRENE.DESCRIPCION_CAUSAL 
        UNION 
        SELECT 
            'GAS' SERVICIO,
            IDENTIFICADOR_EMPRESA,
            CAR_CARG_ANO ANIO, 
            LPAD(FG.CAR_T1552_DANE_DEPTO, 2, 0)||LPAD(FG.CAR_T1552_DANE_MPIO,3,0)||LPAD(FG.CAR_T1552_DANE_CPOBLADO, 3, 0) CODIGO_CENTRO_POBLADO, 
            CAR_T1552_CAUSAL_DETALLE COD_CAUSA,
            PQRGAS.DESCRIPCION_CAUSAL DESC_CAUSA,
            COUNT (DISTINCT(FG.CAR_T1552_RAD_RECIBIDO)) NUMERO_QUEJAS 
        FROM 
            CAR_T1552_RECLAMACIONES_GAS FG, PQR_CAUSAL_GAS PQRGAS  
        WHERE 
                CAR_CARG_ANO = :ANIO_ARG 
            AND FG.CAR_T1552_CAUSAL_DETALLE = PQRGAS.IDENTIFICADOR_CAUSAL  
            AND (IDENTIFICADOR_EMPRESA = :EMPRESA_ARG OR 0 = :EMPRESA_ARG)
            AND (CAR_CARG_PERIODO = :PERIODO_ARG OR :PERIODO_ARG = 0 ) 
            AND ( 'GAS' = :SERVICIO_ARG OR 'TODOS' = :SERVICIO_ARG ) 
            AND ( CAR_T1552_CAUSAL_DETALLE = :CAUSA_ARG OR :CAUSA_ARG = 0 ) 
        GROUP BY IDENTIFICADOR_EMPRESA,CAR_CARG_ANO, LPAD(FG.CAR_T1552_DANE_DEPTO, 2, 0)||LPAD(FG.CAR_T1552_DANE_MPIO,3,0)||LPAD(FG.CAR_T1552_DANE_CPOBLADO, 3, 0), CAR_T1552_CAUSAL_DETALLE, PQRGAS.DESCRIPCION_CAUSAL 
        UNION 
        SELECT 
            'GLP' SERVICIO,
            IDENTIFICADOR_EMPRESA,
            CAR_CARG_ANO ANIO, 
            LPAD(FGL.CAR_T1554_DANE_DEPTO, 2, 0)||LPAD(FGL.CAR_T1554_DANE_MPIO,3,0)||LPAD(FGL.CAR_T1554_DANE_CPOBLADO, 3, 0) CODIGO_CENTRO_POBLADO, 
            FGL.CAR_T1554_CAUSAL_DETALLE COD_CAUSA,
            PQRGLP.DESCRIPCION_CAUSAL DESC_CAUSA,
            COUNT (DISTINCT(FGL.CAR_T1554_RAD_RECIBIDO)) NUMERO_QUEJAS 
        FROM 
            CAR_T1554_RECLAMACIONES_GLP FGL, PQR_CAUSAL_GLP PQRGLP  
        WHERE 
                CAR_CARG_ANO = :ANIO_ARG 
            AND FGL.CAR_T1554_CAUSAL_DETALLE = PQRGLP.IDENTIFICADOR_CAUSAL                
            AND (IDENTIFICADOR_EMPRESA = :EMPRESA_ARG OR 0 = :EMPRESA_ARG)
            AND (CAR_CARG_PERIODO = :PERIODO_ARG OR :PERIODO_ARG = 0 ) 
            AND ( 'GLP' = :SERVICIO_ARG OR 'TODOS' = :SERVICIO_ARG )
            AND ( CAR_T1554_CAUSAL_DETALLE = :CAUSA_ARG OR :CAUSA_ARG = 0 ) 
        GROUP BY IDENTIFICADOR_EMPRESA,CAR_CARG_ANO, LPAD(FGL.CAR_T1554_DANE_DEPTO, 2, 0)||LPAD(FGL.CAR_T1554_DANE_MPIO,3,0)||LPAD(FGL.CAR_T1554_DANE_CPOBLADO, 3, 0), CAR_T1554_CAUSAL_DETALLE, PQRGLP.DESCRIPCION_CAUSAL  
    ) Q, 
    GIS_CENTRO_POBLADO G, ARE_ESP_EMPRESAS EMP  
WHERE G.CODIGO_CENTRO_POBLADO = Q.CODIGO_CENTRO_POBLADO 
AND IDENTIFICADOR_EMPRESA = ARE_ESP_SECUE 
GROUP BY SERVICIO,IDENTIFICADOR_EMPRESA,ARE_ESP_NOMBRE,NOMBRE_CENTRO_POBLADO,COD_CAUSA,DESC_CAUSA,LATITUD,LONGITUD
ORDER BY NUMERO DESC;